---
- name: install libraries for redmine
  yum: state=present name={{ item }}
  with_items:
    - curl-devel
    - ImageMagick 
    - ImageMagick-devel 
    - ipa-pgothic-fonts

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: checkout Redmine
  sudo: yes
  subversion:
    repo={{ redmine_svn_url }}
    dest={{ redmine_dir }}

- name: copy database.yml
  sudo: yes
  template:
    src=database.yml.j2
    dest={{ redmine_dir }}/config/database.yml
    force=no
  register:
    result_database_yml

- name: copy configuration.yml
  sudo: yes
  template:
    src=configuration.yml.j2
    dest={{ redmine_dir }}/config/configuration.yml
    force=no

- name: check if Gemfile.lock exists
  command:
    test -f {{ redmine_dir }}/Gemfile.lock
  register:
    result_test_gemfile
  failed_when: result_test_gemfile.rc not in [0, 1]
  changed_when: false

- name: install gems packages
  sudo: yes
  shell: $SHELL -lc "bundle install --path vendor/bundle"
  args:
    chdir: "{{ redmine_dir }}"
  when:
    result_test_gemfile.rc == 1

- name: update gems packages
  sudo: yes
  shell: $SHELL -lc "bundle update"
  args:
    chdir: "{{ redmine_dir }}"
  when:
    result_test_gemfile.rc == 0

- name: create a secret token
  sudo: yes
  shell: $SHELL -lc "bundle exec rake generate_secret_token"
  args: 
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production


- name: データベースのマイグレーション
  sudo: yes
  shell: $SHELL -lc "bundle exec rake db:migrate"
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production

- name: デフォルトデータ(日本語)をロード
  sudo: yes
  shell: $SHELL -lc "bundle exec rake redmine:load_default_data"
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
    REDMINE_LANG: ja
  when:
    result_database_yml|changed

- name: 添付ファイルとリポジトリのエンコーディングを設定
  sudo: yes
  shell: $SHELL -lc "bundle exec rails r 'Setting[\"repositories_encodings\"]=\"UTF-8,CP932,EUC-JP\"'"
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
  when:
    result_database_yml|changed

- name: 添付ファイルのサムネイルを表示
  sudo: yes
  shell: $SHELL -lc "bundle exec rails r 'Setting[\"thumbnails_enabled\"]=\"1\"'"
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
  when:
    result_database_yml|changed
